package net.minecraft.world.damagesource;

import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstapContext;
import net.minecraft.resources.MinecraftKey;
import net.minecraft.resources.ResourceKey;

public interface DamageTypes {
   ResourceKey<DamageType> a = ResourceKey.a(Registries.o, new MinecraftKey("in_fire"));
   ResourceKey<DamageType> b = ResourceKey.a(Registries.o, new MinecraftKey("lightning_bolt"));
   ResourceKey<DamageType> c = ResourceKey.a(Registries.o, new MinecraftKey("on_fire"));
   ResourceKey<DamageType> d = ResourceKey.a(Registries.o, new MinecraftKey("lava"));
   ResourceKey<DamageType> e = ResourceKey.a(Registries.o, new MinecraftKey("hot_floor"));
   ResourceKey<DamageType> f = ResourceKey.a(Registries.o, new MinecraftKey("in_wall"));
   ResourceKey<DamageType> g = ResourceKey.a(Registries.o, new MinecraftKey("cramming"));
   ResourceKey<DamageType> h = ResourceKey.a(Registries.o, new MinecraftKey("drown"));
   ResourceKey<DamageType> i = ResourceKey.a(Registries.o, new MinecraftKey("starve"));
   ResourceKey<DamageType> j = ResourceKey.a(Registries.o, new MinecraftKey("cactus"));
   ResourceKey<DamageType> k = ResourceKey.a(Registries.o, new MinecraftKey("fall"));
   ResourceKey<DamageType> l = ResourceKey.a(Registries.o, new MinecraftKey("fly_into_wall"));
   ResourceKey<DamageType> m = ResourceKey.a(Registries.o, new MinecraftKey("out_of_world"));
   ResourceKey<DamageType> n = ResourceKey.a(Registries.o, new MinecraftKey("generic"));
   ResourceKey<DamageType> o = ResourceKey.a(Registries.o, new MinecraftKey("magic"));
   ResourceKey<DamageType> p = ResourceKey.a(Registries.o, new MinecraftKey("wither"));
   ResourceKey<DamageType> q = ResourceKey.a(Registries.o, new MinecraftKey("dragon_breath"));
   ResourceKey<DamageType> r = ResourceKey.a(Registries.o, new MinecraftKey("dry_out"));
   ResourceKey<DamageType> s = ResourceKey.a(Registries.o, new MinecraftKey("sweet_berry_bush"));
   ResourceKey<DamageType> t = ResourceKey.a(Registries.o, new MinecraftKey("freeze"));
   ResourceKey<DamageType> u = ResourceKey.a(Registries.o, new MinecraftKey("stalagmite"));
   ResourceKey<DamageType> v = ResourceKey.a(Registries.o, new MinecraftKey("falling_block"));
   ResourceKey<DamageType> w = ResourceKey.a(Registries.o, new MinecraftKey("falling_anvil"));
   ResourceKey<DamageType> x = ResourceKey.a(Registries.o, new MinecraftKey("falling_stalactite"));
   ResourceKey<DamageType> y = ResourceKey.a(Registries.o, new MinecraftKey("sting"));
   ResourceKey<DamageType> z = ResourceKey.a(Registries.o, new MinecraftKey("mob_attack"));
   ResourceKey<DamageType> A = ResourceKey.a(Registries.o, new MinecraftKey("mob_attack_no_aggro"));
   ResourceKey<DamageType> B = ResourceKey.a(Registries.o, new MinecraftKey("player_attack"));
   ResourceKey<DamageType> C = ResourceKey.a(Registries.o, new MinecraftKey("arrow"));
   ResourceKey<DamageType> D = ResourceKey.a(Registries.o, new MinecraftKey("trident"));
   ResourceKey<DamageType> E = ResourceKey.a(Registries.o, new MinecraftKey("mob_projectile"));
   ResourceKey<DamageType> F = ResourceKey.a(Registries.o, new MinecraftKey("fireworks"));
   ResourceKey<DamageType> G = ResourceKey.a(Registries.o, new MinecraftKey("fireball"));
   ResourceKey<DamageType> H = ResourceKey.a(Registries.o, new MinecraftKey("unattributed_fireball"));
   ResourceKey<DamageType> I = ResourceKey.a(Registries.o, new MinecraftKey("wither_skull"));
   ResourceKey<DamageType> J = ResourceKey.a(Registries.o, new MinecraftKey("thrown"));
   ResourceKey<DamageType> K = ResourceKey.a(Registries.o, new MinecraftKey("indirect_magic"));
   ResourceKey<DamageType> L = ResourceKey.a(Registries.o, new MinecraftKey("thorns"));
   ResourceKey<DamageType> M = ResourceKey.a(Registries.o, new MinecraftKey("explosion"));
   ResourceKey<DamageType> N = ResourceKey.a(Registries.o, new MinecraftKey("player_explosion"));
   ResourceKey<DamageType> O = ResourceKey.a(Registries.o, new MinecraftKey("sonic_boom"));
   ResourceKey<DamageType> P = ResourceKey.a(Registries.o, new MinecraftKey("bad_respawn_point"));

   static void a(BootstapContext<DamageType> var0) {
      var0.a(a, new DamageType("inFire", 0.1F, DamageEffects.d));
      var0.a(b, new DamageType("lightningBolt", 0.1F));
      var0.a(c, new DamageType("onFire", 0.0F, DamageEffects.d));
      var0.a(d, new DamageType("lava", 0.1F, DamageEffects.d));
      var0.a(e, new DamageType("hotFloor", 0.1F, DamageEffects.d));
      var0.a(f, new DamageType("inWall", 0.0F));
      var0.a(g, new DamageType("cramming", 0.0F));
      var0.a(h, new DamageType("drown", 0.0F, DamageEffects.c));
      var0.a(i, new DamageType("starve", 0.0F));
      var0.a(j, new DamageType("cactus", 0.1F));
      var0.a(k, new DamageType("fall", DamageScaling.b, 0.0F, DamageEffects.a, DeathMessageType.b));
      var0.a(l, new DamageType("flyIntoWall", 0.0F));
      var0.a(m, new DamageType("outOfWorld", 0.0F));
      var0.a(n, new DamageType("generic", 0.0F));
      var0.a(o, new DamageType("magic", 0.0F));
      var0.a(p, new DamageType("wither", 0.0F));
      var0.a(q, new DamageType("dragonBreath", 0.0F));
      var0.a(r, new DamageType("dryout", 0.1F));
      var0.a(s, new DamageType("sweetBerryBush", 0.1F, DamageEffects.e));
      var0.a(t, new DamageType("freeze", 0.0F, DamageEffects.f));
      var0.a(u, new DamageType("stalagmite", 0.0F));
      var0.a(v, new DamageType("fallingBlock", 0.1F));
      var0.a(w, new DamageType("anvil", 0.1F));
      var0.a(x, new DamageType("fallingStalactite", 0.1F));
      var0.a(y, new DamageType("sting", 0.1F));
      var0.a(z, new DamageType("mob", 0.1F));
      var0.a(A, new DamageType("mob", 0.1F));
      var0.a(B, new DamageType("player", 0.1F));
      var0.a(C, new DamageType("arrow", 0.1F));
      var0.a(D, new DamageType("trident", 0.1F));
      var0.a(E, new DamageType("mob", 0.1F));
      var0.a(F, new DamageType("fireworks", 0.1F));
      var0.a(H, new DamageType("onFire", 0.1F, DamageEffects.d));
      var0.a(G, new DamageType("fireball", 0.1F, DamageEffects.d));
      var0.a(I, new DamageType("witherSkull", 0.1F));
      var0.a(J, new DamageType("thrown", 0.1F));
      var0.a(K, new DamageType("indirectMagic", 0.0F));
      var0.a(L, new DamageType("thorns", 0.1F, DamageEffects.b));
      var0.a(M, new DamageType("explosion", DamageScaling.c, 0.1F));
      var0.a(N, new DamageType("explosion.player", DamageScaling.c, 0.1F));
      var0.a(O, new DamageType("sonic_boom", DamageScaling.c, 0.0F));
      var0.a(P, new DamageType("badRespawnPoint", DamageScaling.c, 0.1F, DamageEffects.a, DeathMessageType.c));
   }
}
