package net.minecraft.core.registries;

import com.mojang.serialization.Codec;
import net.minecraft.commands.synchronization.ArgumentTypeInfo;
import net.minecraft.core.IRegistry;
import net.minecraft.core.particles.Particle;
import net.minecraft.network.chat.ChatMessageType;
import net.minecraft.resources.MinecraftKey;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEffect;
import net.minecraft.stats.StatisticWrapper;
import net.minecraft.util.valueproviders.FloatProviderType;
import net.minecraft.util.valueproviders.IntProviderType;
import net.minecraft.world.damagesource.DamageType;
import net.minecraft.world.effect.MobEffectList;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.entity.ai.attributes.AttributeBase;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.ai.sensing.SensorType;
import net.minecraft.world.entity.ai.village.poi.VillagePlaceType;
import net.minecraft.world.entity.animal.CatVariant;
import net.minecraft.world.entity.animal.FrogVariant;
import net.minecraft.world.entity.decoration.PaintingVariant;
import net.minecraft.world.entity.npc.VillagerProfession;
import net.minecraft.world.entity.npc.VillagerType;
import net.minecraft.world.entity.schedule.Activity;
import net.minecraft.world.entity.schedule.Schedule;
import net.minecraft.world.inventory.Containers;
import net.minecraft.world.item.Instrument;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.alchemy.PotionRegistry;
import net.minecraft.world.item.armortrim.TrimMaterial;
import net.minecraft.world.item.armortrim.TrimPattern;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.item.crafting.Recipes;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.level.World;
import net.minecraft.world.level.biome.BiomeBase;
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterList;
import net.minecraft.world.level.biome.WorldChunkManager;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.entity.EnumBannerPatternType;
import net.minecraft.world.level.block.entity.TileEntityTypes;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.chunk.ChunkStatus;
import net.minecraft.world.level.dimension.DimensionManager;
import net.minecraft.world.level.dimension.WorldDimension;
import net.minecraft.world.level.gameevent.GameEvent;
import net.minecraft.world.level.gameevent.PositionSourceType;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.GeneratorSettingBase;
import net.minecraft.world.level.levelgen.SurfaceRules;
import net.minecraft.world.level.levelgen.blockpredicates.BlockPredicateType;
import net.minecraft.world.level.levelgen.carver.WorldGenCarverAbstract;
import net.minecraft.world.level.levelgen.carver.WorldGenCarverWrapper;
import net.minecraft.world.level.levelgen.feature.WorldGenFeatureConfigured;
import net.minecraft.world.level.levelgen.feature.WorldGenerator;
import net.minecraft.world.level.levelgen.feature.featuresize.FeatureSizeType;
import net.minecraft.world.level.levelgen.feature.foliageplacers.WorldGenFoilagePlacers;
import net.minecraft.world.level.levelgen.feature.rootplacers.RootPlacerType;
import net.minecraft.world.level.levelgen.feature.stateproviders.WorldGenFeatureStateProviders;
import net.minecraft.world.level.levelgen.feature.treedecorators.WorldGenFeatureTrees;
import net.minecraft.world.level.levelgen.feature.trunkplacers.TrunkPlacers;
import net.minecraft.world.level.levelgen.flat.FlatLevelGeneratorPreset;
import net.minecraft.world.level.levelgen.heightproviders.HeightProviderType;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.levelgen.placement.PlacementModifierType;
import net.minecraft.world.level.levelgen.presets.WorldPreset;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.StructureSet;
import net.minecraft.world.level.levelgen.structure.StructureType;
import net.minecraft.world.level.levelgen.structure.pieces.WorldGenFeatureStructurePieceType;
import net.minecraft.world.level.levelgen.structure.placement.StructurePlacementType;
import net.minecraft.world.level.levelgen.structure.pools.WorldGenFeatureDefinedStructurePoolTemplate;
import net.minecraft.world.level.levelgen.structure.pools.WorldGenFeatureDefinedStructurePools;
import net.minecraft.world.level.levelgen.structure.templatesystem.DefinedStructureRuleTestType;
import net.minecraft.world.level.levelgen.structure.templatesystem.DefinedStructureStructureProcessorType;
import net.minecraft.world.level.levelgen.structure.templatesystem.PosRuleTestType;
import net.minecraft.world.level.levelgen.structure.templatesystem.ProcessorList;
import net.minecraft.world.level.levelgen.synth.NoiseGeneratorNormal;
import net.minecraft.world.level.material.FluidType;
import net.minecraft.world.level.storage.loot.entries.LootEntryType;
import net.minecraft.world.level.storage.loot.functions.LootItemFunctionType;
import net.minecraft.world.level.storage.loot.predicates.LootItemConditionType;
import net.minecraft.world.level.storage.loot.providers.nbt.LootNbtProviderType;
import net.minecraft.world.level.storage.loot.providers.number.LootNumberProviderType;
import net.minecraft.world.level.storage.loot.providers.score.LootScoreProviderType;

public class Registries {
   public static final ResourceKey<IRegistry<Activity>> a = a("activity");
   public static final ResourceKey<IRegistry<AttributeBase>> b = a("attribute");
   public static final ResourceKey<IRegistry<EnumBannerPatternType>> c = a("banner_pattern");
   public static final ResourceKey<IRegistry<Codec<? extends WorldChunkManager>>> d = a("worldgen/biome_source");
   public static final ResourceKey<IRegistry<Block>> e = a("block");
   public static final ResourceKey<IRegistry<TileEntityTypes<?>>> f = a("block_entity_type");
   public static final ResourceKey<IRegistry<BlockPredicateType<?>>> g = a("block_predicate_type");
   public static final ResourceKey<IRegistry<WorldGenFeatureStateProviders<?>>> h = a("worldgen/block_state_provider_type");
   public static final ResourceKey<IRegistry<WorldGenCarverAbstract<?>>> i = a("worldgen/carver");
   public static final ResourceKey<IRegistry<CatVariant>> j = a("cat_variant");
   public static final ResourceKey<IRegistry<Codec<? extends ChunkGenerator>>> k = a("worldgen/chunk_generator");
   public static final ResourceKey<IRegistry<ChunkStatus>> l = a("chunk_status");
   public static final ResourceKey<IRegistry<ArgumentTypeInfo<?, ?>>> m = a("command_argument_type");
   public static final ResourceKey<IRegistry<MinecraftKey>> n = a("custom_stat");
   public static final ResourceKey<IRegistry<DamageType>> o = a("damage_type");
   public static final ResourceKey<IRegistry<Codec<? extends DensityFunction>>> p = a("worldgen/density_function_type");
   public static final ResourceKey<IRegistry<Enchantment>> q = a("enchantment");
   public static final ResourceKey<IRegistry<EntityTypes<?>>> r = a("entity_type");
   public static final ResourceKey<IRegistry<WorldGenerator<?>>> s = a("worldgen/feature");
   public static final ResourceKey<IRegistry<FeatureSizeType<?>>> t = a("worldgen/feature_size_type");
   public static final ResourceKey<IRegistry<FloatProviderType<?>>> u = a("float_provider_type");
   public static final ResourceKey<IRegistry<FluidType>> v = a("fluid");
   public static final ResourceKey<IRegistry<WorldGenFoilagePlacers<?>>> w = a("worldgen/foliage_placer_type");
   public static final ResourceKey<IRegistry<FrogVariant>> x = a("frog_variant");
   public static final ResourceKey<IRegistry<GameEvent>> y = a("game_event");
   public static final ResourceKey<IRegistry<HeightProviderType<?>>> z = a("height_provider_type");
   public static final ResourceKey<IRegistry<Instrument>> A = a("instrument");
   public static final ResourceKey<IRegistry<IntProviderType<?>>> B = a("int_provider_type");
   public static final ResourceKey<IRegistry<Item>> C = a("item");
   public static final ResourceKey<IRegistry<LootItemConditionType>> D = a("loot_condition_type");
   public static final ResourceKey<IRegistry<LootItemFunctionType>> E = a("loot_function_type");
   public static final ResourceKey<IRegistry<LootNbtProviderType>> F = a("loot_nbt_provider_type");
   public static final ResourceKey<IRegistry<LootNumberProviderType>> G = a("loot_number_provider_type");
   public static final ResourceKey<IRegistry<LootEntryType>> H = a("loot_pool_entry_type");
   public static final ResourceKey<IRegistry<LootScoreProviderType>> I = a("loot_score_provider_type");
   public static final ResourceKey<IRegistry<Codec<? extends SurfaceRules.f>>> J = a("worldgen/material_condition");
   public static final ResourceKey<IRegistry<Codec<? extends SurfaceRules.o>>> K = a("worldgen/material_rule");
   public static final ResourceKey<IRegistry<MemoryModuleType<?>>> L = a("memory_module_type");
   public static final ResourceKey<IRegistry<Containers<?>>> M = a("menu");
   public static final ResourceKey<IRegistry<MobEffectList>> N = a("mob_effect");
   public static final ResourceKey<IRegistry<PaintingVariant>> O = a("painting_variant");
   public static final ResourceKey<IRegistry<Particle<?>>> P = a("particle_type");
   public static final ResourceKey<IRegistry<PlacementModifierType<?>>> Q = a("worldgen/placement_modifier_type");
   public static final ResourceKey<IRegistry<VillagePlaceType>> R = a("point_of_interest_type");
   public static final ResourceKey<IRegistry<PositionSourceType<?>>> S = a("position_source_type");
   public static final ResourceKey<IRegistry<PosRuleTestType<?>>> T = a("pos_rule_test");
   public static final ResourceKey<IRegistry<PotionRegistry>> U = a("potion");
   public static final ResourceKey<IRegistry<RecipeSerializer<?>>> V = a("recipe_serializer");
   public static final ResourceKey<IRegistry<Recipes<?>>> W = a("recipe_type");
   public static final ResourceKey<IRegistry<RootPlacerType<?>>> X = a("worldgen/root_placer_type");
   public static final ResourceKey<IRegistry<DefinedStructureRuleTestType<?>>> Y = a("rule_test");
   public static final ResourceKey<IRegistry<Schedule>> Z = a("schedule");
   public static final ResourceKey<IRegistry<SensorType<?>>> aa = a("sensor_type");
   public static final ResourceKey<IRegistry<SoundEffect>> ab = a("sound_event");
   public static final ResourceKey<IRegistry<StatisticWrapper<?>>> ac = a("stat_type");
   public static final ResourceKey<IRegistry<WorldGenFeatureStructurePieceType>> ad = a("worldgen/structure_piece");
   public static final ResourceKey<IRegistry<StructurePlacementType<?>>> ae = a("worldgen/structure_placement");
   public static final ResourceKey<IRegistry<WorldGenFeatureDefinedStructurePools<?>>> af = a("worldgen/structure_pool_element");
   public static final ResourceKey<IRegistry<DefinedStructureStructureProcessorType<?>>> ag = a("worldgen/structure_processor");
   public static final ResourceKey<IRegistry<StructureType<?>>> ah = a("worldgen/structure_type");
   public static final ResourceKey<IRegistry<WorldGenFeatureTrees<?>>> ai = a("worldgen/tree_decorator_type");
   public static final ResourceKey<IRegistry<TrunkPlacers<?>>> aj = a("worldgen/trunk_placer_type");
   public static final ResourceKey<IRegistry<VillagerProfession>> ak = a("villager_profession");
   public static final ResourceKey<IRegistry<VillagerType>> al = a("villager_type");
   public static final ResourceKey<IRegistry<String>> am = a("decorated_pot_patterns");
   public static final ResourceKey<IRegistry<BiomeBase>> an = a("worldgen/biome");
   public static final ResourceKey<IRegistry<ChatMessageType>> ao = a("chat_type");
   public static final ResourceKey<IRegistry<WorldGenCarverWrapper<?>>> ap = a("worldgen/configured_carver");
   public static final ResourceKey<IRegistry<WorldGenFeatureConfigured<?, ?>>> aq = a("worldgen/configured_feature");
   public static final ResourceKey<IRegistry<DensityFunction>> ar = a("worldgen/density_function");
   public static final ResourceKey<IRegistry<DimensionManager>> as = a("dimension_type");
   public static final ResourceKey<IRegistry<FlatLevelGeneratorPreset>> at = a("worldgen/flat_level_generator_preset");
   public static final ResourceKey<IRegistry<GeneratorSettingBase>> au = a("worldgen/noise_settings");
   public static final ResourceKey<IRegistry<NoiseGeneratorNormal.a>> av = a("worldgen/noise");
   public static final ResourceKey<IRegistry<PlacedFeature>> aw = a("worldgen/placed_feature");
   public static final ResourceKey<IRegistry<Structure>> ax = a("worldgen/structure");
   public static final ResourceKey<IRegistry<ProcessorList>> ay = a("worldgen/processor_list");
   public static final ResourceKey<IRegistry<StructureSet>> az = a("worldgen/structure_set");
   public static final ResourceKey<IRegistry<WorldGenFeatureDefinedStructurePoolTemplate>> aA = a("worldgen/template_pool");
   public static final ResourceKey<IRegistry<TrimMaterial>> aB = a("trim_material");
   public static final ResourceKey<IRegistry<TrimPattern>> aC = a("trim_pattern");
   public static final ResourceKey<IRegistry<WorldPreset>> aD = a("worldgen/world_preset");
   public static final ResourceKey<IRegistry<MultiNoiseBiomeSourceParameterList>> aE = a("worldgen/multi_noise_biome_source_parameter_list");
   public static final ResourceKey<IRegistry<World>> aF = a("dimension");
   public static final ResourceKey<IRegistry<WorldDimension>> aG = a("dimension");

   public static ResourceKey<World> a(ResourceKey<WorldDimension> var0) {
      return ResourceKey.a(aF, var0.a());
   }

   public static ResourceKey<WorldDimension> b(ResourceKey<World> var0) {
      return ResourceKey.a(aG, var0.a());
   }

   private static <T> ResourceKey<IRegistry<T>> a(String var0) {
      return ResourceKey.a(new MinecraftKey(var0));
   }
}
